Repository Vhoyon/Vramework, pull requests merged in 2018-10, with the labels that each got.

#24 Adds the timerManager class
  src/main/java/io/github/vhoyon/vramework/utilities/TimerManager.java
Labels: !Enhancement: Framework, !Priority: Medium

#25 Allow hiding commands in full help String by implementing Hidden interface
  src/main/java/io/github/vhoyon/vramework/abstracts/CommandsLinker.java
  src/main/java/io/github/vhoyon/vramework/interfaces/Hidden.java
Labels: !Feature Request: Framework, !Priority: Low, *verified

#26 Add bot mention handling to AbstractCommandRouter
  src/main/java/io/github/vhoyon/vramework/abstracts/AbstractCommandRouter.java
Labels: !Feature Request: Framework, !Priority: High, *verified
